name: ${NAME}
services:
  nginx:
    image: openresty/openresty:alpine
    container_name: ${NAME}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/letsencrypt:ro
      - ./html:/usr/share/nginx/html:ro
      - ./lua:/etc/nginx/lua:ro
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
