name: Nginx
description: High-performance HTTP server and reverse proxy
icon: pi pi-server
logo: https://cdn.simpleicons.org/nginx
category: infrastructure
type: infrastructure
priority: 100

mounts:
  dirs:
    - conf.d
    - certs
    - html
    - lua
  files:
    - nginx.conf

setup:
  dirs:
    - conf.d
    - certs
    - html
    - lua
  files:
    - src: nginx.conf
      dest: nginx.conf
      overwrite: true
    - src: welcome/index.html
      dest: html/index.html
      overwrite: false
      external: true
    - src: default.conf
      dest: conf.d/default.conf
      overwrite: false
    - dest: conf.d/rate_limits.conf
      overwrite: false
      empty: true
