name: ${NAME}
services:
  app:
    image: php:8.3-apache
    container_name: ${NAME}
    volumes:
      - ./html:/var/www/html
    expose:
      - "80"
    networks:
      - web
    restart: unless-stopped
    env_file:
      - .env.flatrun

networks:
  web:
    external: true
