name: ${NAME}
services:
  app:
    image: php:8.3-apache
    container_name: ${NAME}
    volumes:
      - ./html:/var/www/html
    expose:
      - "80"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
