package api

import (
	_ "embed"
	"net/http"

	"github.com/gin-gonic/gin"
)

// Generated by tools/genspec and checked against the routes in CI. Serving it lets a client ask
// the instance it is talking to what that instance accepts.
//
//go:embed openapi.json
var openAPISpec []byte

func (s *Server) getOpenAPISpec(c *gin.Context) {
	c.Data(http.StatusOK, "application/json; charset=utf-8", openAPISpec)
}
