name: ${NAME}
services:
  app:
    image: bitnami/laravel:latest
    container_name: ${NAME}
    volumes:
      - ./app:/app
    expose:
      - "8000"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
