name: ${NAME}
services:
  minio:
    image: minio/minio:latest
    container_name: ${NAME}
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-flatrun}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-changeme}
    volumes:
      - ./data:/data
    expose:
      - "9000"
      - "9001"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
