name: ${NAME}
services:
  app:
    image: node:20-alpine
    container_name: ${NAME}
    working_dir: /app
    expose:
      - "3000"
    command: npm start
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
