package security

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// NginxConfigGenerator generates nginx security configuration files
type NginxConfigGenerator struct {
	manager    *Manager
	configPath string
}

func NewNginxConfigGenerator(manager *Manager, configPath string) *NginxConfigGenerator {
	return &NginxConfigGenerator{
		manager:    manager,
		configPath: configPath,
	}
}

// GenerateBlockedIPsConfig generates the blocked_ips.conf file
func (g *NginxConfigGenerator) GenerateBlockedIPsConfig() (string, error) {
	blockedIPs, err := g.manager.GetActiveBlockedIPs()
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by FlatRun Security\n")
	buf.WriteString("# Do not edit manually - changes will be overwritten\n\n")

	if len(blockedIPs) == 0 {
		buf.WriteString("# No blocked IPs\n")
	} else {
		for _, ip := range blockedIPs {
			comment := ""
			if ip.Reason != "" {
				comment = fmt.Sprintf(" # %s", ip.Reason)
			}
			buf.WriteString(fmt.Sprintf("deny %s;%s\n", ip.IP, comment))
		}
	}

	return buf.String(), nil
}

// GenerateRateLimitsConfig generates the rate_limits.conf file
func (g *NginxConfigGenerator) GenerateRateLimitsConfig() (string, error) {
	routes, err := g.manager.GetEnabledProtectedRoutes()
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by FlatRun Security\n")
	buf.WriteString("# Do not edit manually - changes will be overwritten\n\n")

	if len(routes) == 0 {
		buf.WriteString("# No rate limit zones defined\n")
		return buf.String(), nil
	}

	// Generate rate limit zones
	buf.WriteString("# Rate limit zones\n")
	for _, route := range routes {
		zoneName := generateZoneName(route.PathPattern)
		rate := fmt.Sprintf("%dr/m", route.RateLimit)
		buf.WriteString(fmt.Sprintf("limit_req_zone $binary_remote_addr zone=%s:10m rate=%s;\n", zoneName, rate))
	}

	return buf.String(), nil
}

// GenerateProtectedLocations generates location blocks for protected routes
func (g *NginxConfigGenerator) GenerateProtectedLocations() (string, error) {
	routes, err := g.manager.GetEnabledProtectedRoutes()
	if err != nil {
		return "", err
	}

	if len(routes) == 0 {
		return "", nil
	}

	var buf bytes.Buffer
	buf.WriteString("\n# Protected routes - rate limiting\n")

	for _, route := range routes {
		zoneName := generateZoneName(route.PathPattern)
		burst := route.RateLimit / 2
		if burst < 1 {
			burst = 1
		}

		// Determine location directive type
		locationDirective := route.PathPattern
		if strings.Contains(route.PathPattern, "*") || strings.Contains(route.PathPattern, "~") {
			locationDirective = fmt.Sprintf("~ %s", strings.ReplaceAll(route.PathPattern, "*", ".*"))
		}

		buf.WriteString(fmt.Sprintf(`location %s {
    limit_req zone=%s burst=%d nodelay;
    limit_req_status 429;
}

`, locationDirective, zoneName, burst))
	}

	return buf.String(), nil
}

// GenerateProtectedPathsConfig generates location blocks for blocked paths
func (g *NginxConfigGenerator) GenerateProtectedPathsConfig(paths []string) string {
	if len(paths) == 0 {
		return ""
	}

	var buf bytes.Buffer
	buf.WriteString("\n# Protected paths - blocked from external access\n")

	for _, path := range paths {
		escapedPath := escapeNginxRegex(path)
		buf.WriteString(fmt.Sprintf("location ~ %s { return 404; }\n", escapedPath))
	}

	return buf.String()
}

// WriteBlockedIPsConfig writes the blocked_ips.conf file
func (g *NginxConfigGenerator) WriteBlockedIPsConfig() error {
	content, err := g.GenerateBlockedIPsConfig()
	if err != nil {
		return err
	}

	filePath := filepath.Join(g.configPath, "blocked_ips.conf")
	return writeIfChanged(filePath, content)
}

// WriteRateLimitsConfig writes the rate_limits.conf file
func (g *NginxConfigGenerator) WriteRateLimitsConfig() error {
	content, err := g.GenerateRateLimitsConfig()
	if err != nil {
		return err
	}

	filePath := filepath.Join(g.configPath, "rate_limits.conf")
	return writeIfChanged(filePath, content)
}

// generateZoneName creates a valid nginx zone name from a path pattern
func generateZoneName(pattern string) string {
	clean := strings.ReplaceAll(pattern, "/", "_")
	clean = strings.ReplaceAll(clean, ".", "_")
	clean = strings.ReplaceAll(clean, "*", "")
	clean = strings.ReplaceAll(clean, "~", "")
	clean = strings.Trim(clean, "_")

	if len(clean) > 20 {
		hash := sha256.Sum256([]byte(pattern))
		clean = "zone_" + hex.EncodeToString(hash[:])[:8]
	}

	if clean == "" {
		clean = "default"
	}

	return clean
}

// escapeNginxRegex escapes special characters for nginx regex
func escapeNginxRegex(path string) string {
	replacer := strings.NewReplacer(
		".", "\\.",
		"*", ".*",
		"$", "\\$",
		"^", "\\^",
		"+", "\\+",
		"?", "\\?",
		"(", "\\(",
		")", "\\)",
		"[", "\\[",
		"]", "\\]",
		"{", "\\{",
		"}", "\\}",
		"|", "\\|",
	)
	return replacer.Replace(path)
}

// writeIfChanged writes content to file only if it's different from existing content
func writeIfChanged(filePath, content string) error {
	existing, err := os.ReadFile(filePath)
	if err == nil && string(existing) == content {
		return nil
	}

	dir := filepath.Dir(filePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	return os.WriteFile(filePath, []byte(content), 0644)
}

// LuaSecurityScript is the Lua script template for real-time security event capture
const LuaSecurityScript = `-- FlatRun Security Event Capture
-- This script captures security-relevant events and sends them to the agent API

local cjson = require "cjson"
local http = require "resty.http"

local AGENT_URL = "{{.AgentURL}}"

-- Suspicious paths patterns
local suspicious_patterns = {
    "%.env",
    "%.git",
    "wp%-admin",
    "wp%-login",
    "wp%-config",
    "phpmyadmin",
    "adminer",
    "/admin",
    "/shell",
    "/cmd",
    "%.sql",
    "%.bak",
    "%.backup",
    "/actuator",
    "/swagger",
}

local function is_suspicious_path(uri)
    local uri_lower = string.lower(uri)
    for _, pattern in ipairs(suspicious_patterns) do
        if string.find(uri_lower, pattern) then
            return true
        end
    end
    return false
end

local function capture_event()
    local status = ngx.status
    local uri = ngx.var.uri
    local ip = ngx.var.remote_addr
    local method = ngx.var.request_method
    local user_agent = ngx.var.http_user_agent or ""
    local host = ngx.var.host or ""

    -- Only capture security-relevant events
    local should_capture = false

    if status == 401 or status == 403 or status == 429 then
        should_capture = true
    elseif status >= 500 then
        should_capture = true
    elseif status == 404 and is_suspicious_path(uri) then
        should_capture = true
    elseif is_suspicious_path(uri) and status ~= 200 then
        should_capture = true
    end

    if not should_capture then
        return
    end

    -- Send event to agent API (non-blocking)
    ngx.timer.at(0, function()
        local httpc = http.new()
        httpc:set_timeout(5000)

        local body = cjson.encode({
            source_ip = ip,
            request_path = uri,
            request_method = method,
            status_code = status,
            user_agent = user_agent,
            deployment_name = host,
            timestamp = ngx.time()
        })

        local res, err = httpc:request_uri(AGENT_URL .. "/api/security/events/ingest", {
            method = "POST",
            body = body,
            headers = {
                ["Content-Type"] = "application/json",
            }
        })

        if not res then
            ngx.log(ngx.ERR, "Failed to send security event: ", err)
        end

        httpc:close()
    end)
end

return {
    capture_event = capture_event,
    is_suspicious_path = is_suspicious_path,
}
`

// GenerateLuaScript generates the security.lua file
func GenerateLuaScript(agentURL string) (string, error) {
	tmpl, err := template.New("lua").Parse(LuaSecurityScript)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, struct {
		AgentURL string
	}{
		AgentURL: agentURL,
	})
	if err != nil {
		return "", err
	}

	return buf.String(), nil
}
